# Generated by Django 5.2.17 on 2026-08-17 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("MEDICINE_UNAVAILABLE", "Medicine Unavailable"),
                            ("INCORRECT_PRICE", "Incorrect Medicine Price"),
                            ("PHARMACY_ISSUE", "Pharmacy Issue"),
                            ("EXPIRED_MEDICINE", "Expired Medicine"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "pharmacy_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField()),
                (
                    "citizen_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
